#!/usr/bin/env python3.4

"""
This program is intended to run Twisted's test suite under Python 3. As such,
it should go away once Twisted has been fully ported to Python 3. It is only
intended to be used from a Twisted checkout, and implementation can and will
change at any time.
"""

import sys, os, unittest, tempfile

from txtulip import reactor
reactor.install()

from twisted.python import log
log.startLogging(sys.stdout)

if sys.argv[1:]:
    testModules = sys.argv[1:]
else:
    modules = {}
    path = os.path.join(twistedPath, "twisted", "python", "dist3.py")
    with open(path) as dist3:
        data = dist3.read()
        code = compile(data, "dist3.py", "exec")
        exec(code, modules)
    testModules = modules["testModules"]

# Avoid dumping trash all over the place
os.chdir(tempfile.mkdtemp(prefix="tw-py3-"))

# Run the tests
unittest.main(module=None, argv=["run-python3-tests", "-v"] + testModules)
